config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "homes/about" => "homes#about", as: "about"
  get "ranks/rank" => "ranks#rank", as: "rank"
  resources :users
  resources :departures
  get "users/departure" => "users#departure", as: "dep"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departure.rb
class Departure < ApplicationRecord
    belongs_to :user
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :departure, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
        departures_path
    end
    
    def after_sign_out_path_for(resource)
        about_path
    end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gerende, :sail_no])
  end
end

app/controllers/dep_detail_controller.rb
class DepDetailController < ApplicationController
  def detail
  end
end

app/controllers/departures_controller.rb
class DeparturesController < ApplicationController
  def index
        @start_date = Date.current
        @end_date = @start_date + 1.day
        @departures = Departure.where(date: @start_date..@end_date).group_by(&:date)
        
        #今週の 未出艇者を出す
        this_week = Time.current.all_week
        this_week_depper = User.joins(:departure).where(departure: { date: this_week })
        @non_depper = User.where.not(id: this_week_depper.pluck(:id))
        
  end
  
  
  def new
    @departure = Departure.new(date: params[:date])
  end
  
  def create
    @departure = Departure.new(departure_params)
    @departure.user_id = current_user.id
    @departure.save
    redirect_to departures_path
  end

  
  
  def edit
    @departure = Departure.find(params[:id])
  end
  
  def update
    @departure = Departure.find(params[:id])
    @departure.update(departure_params)
    redirect_to departures_path
   
  end
  
  def destroy 
    departure = Departure.find(params[:id])
    departure.destroy
    redirect_to departures_path
  end
  
  private
  
  def departure_params
    params.require(:departure).permit(:user_id, :start_time, :end_time, :date, :comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
    def rank
        @this_month = Time.current.all_month
        @user_rank = User.where(id: Departure.where(date: @this_month).group(:user_id).order('count(user_id) desc').pluck(:user_id))
        
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index 
        @users = User.all
        
    end
    
    def show
        @user = User.find(params[:id])
        @departure = @user.departure
        
        #今月のレンジ
        this_month = Time.current.all_month
        # 今月の出艇
        @departure_month = @departure.where(date: this_month)
    end
    
    def edit
        @user = User.find(params[:id])
    end
    
    def update 
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to user_path
    end
    
    def destroy 
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end
    
    private
    
    def user_params
        params.require(:user).permit(:name, :profile_image, :sail_no, :gerende)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dep_detail_helper.rb
module DepDetailHelper
end

app/helpers/departures_helper.rb
module DeparturesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/departures/edit.html.erb
<h1>出艇編集</h1>
<div>
    <%= form_with model: @departure do |f| %>
        <%= f.hidden_field :date %>
        <h4><%= @departure.date %></h4>
        <h4><%= current_user.name %></h4>
        <h4>開始時間</h4>
        <%= f.time_select :start_time  %>
    
        <h4>終了時間</h4>
        <%= f.time_select :end_time %>
    
        <h4>コメント</h4>
        <%= f.text_area :comment %>
    
        <%= f.submit "登録" %>
        <% end %>
</div>

app/views/departures/index.html.erb
<div class="container mt-1 text-center">
  <div class="row mb-3">
        <a href="https://www6.kaiho.mlit.go.jp/03kanku/yokohama/kisyou.html" class="btn btn-primary" target="_blank">海上保安庁風速</a>
  </div>
    <% (@start_date..@end_date).each do |date| %>
    
      <div>
        <h3 class="text-center"><%= link_to date, new_departure_path(date: date),class: 'btn btn-secondary btn-lg'%></h3>
      </div>
      <div class="border border-secondary mb-4">
      <% if @departures[date].present? %>
        <% @departures[date].each do |event| %>
          <div class="card mb-2 mt-2" style="width:60%; margin: auto;">
            <div class="text-center">
              <h4><%= image_tag event.user.get_profile_image(30, 30), class: "rounded-circle" %><%= event.user.name %> <%= event.user.sail_no %></h4>
              <div><%= event.start_time.strftime("%H:%M") %>~<%= event.end_time.strftime("%H:%M") %></div>
              <div><%= event.comment %></div>
              <% if event.user == current_user %>
                <%= link_to "削除", departure_path(event), method: :delete %>
                <%= link_to "編集", edit_departure_path(event) %>
              <% end %>
            </div>
          </div>
        <% end %>      
        <% else %>   
          <h4 class="text-center">出艇者はいません</h4>  
      <% end %> 
    </div>
    <% end %>
    
  <% if Date.current.wday == 0 %>
  <div>
    <h1>未出艇者</h1>
    <ul>
      <% @non_depper.each do |user| %>
        <li><%= user.name %></li>
      <% end %>
    </ul>
  </div>
  <% else %>
  <div> </div>
  <% end %>
</div>


  

app/views/departures/new.html.erb
<div class="container text-center mt-5">
    <h1>新規出艇</h1>
    <%= form_with model: @departure do |f| %>
    <%= f.hidden_field :date %>
    <h4><%= @departure.date %></h4>
    <h4><%= current_user.name %></h4>
    <h4>開始時間</h4>
    <%= f.time_select :start_time  %>
    
    <h4>終了時間</h4>
    <%= f.time_select :end_time %>
    
    <h4>コメント</h4>
    <%= f.text_area :comment %>
    <div>
        <%= f.submit "登録" %>
    </div>
    <% end %>
</div>

app/views/homes/about.html.erb
<h1>about</h1>

app/views/homes/top.html.erb
    <div class="col-md-6 mx-auto mt-5">
        <h1>ウィンドサーフィン出艇アプリ</h1>
        <div class="row">
           <p class="ml-3"><a class="btn btn-info" href="/users/sign_in">Log in</a></p>
           <p class="ml-3"><a class="btn btn-success" href="/users/sign_up">Sign Up</a></p>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Windsurfing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <script src="https://kit.fontawesome.com/xxxxxxxxxx.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/5b7ca87169.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/departures">MIURA WINDSURFING</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "ランキング", rank_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "出艇", departures_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "メンバー", users_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main class="mb-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/ranks/rank.html.erb
 <div class="container"> 
  <h3 class="mt-2 mb-5"><i class="fa-solid fa-crown"></i>月間出艇回数ランキング</h2>
    <table class="table text-center">
      <thead>
        <tr>
          <th>順位</th>
          <th>名前</th>
          <th>回数</th>
        </tr>
      </thead>
        <% @user_rank.each.with_index(1) do |user, index| %>
      <tbody>
        <tr>
          <td><%= index %>位</td>
          <td><%= user.name %></td>
          <td><%= user.departure.where(date: @this_month).count %>回</td>
        </tr>
      </tbody>
        <% end %>
    </table>
  </div>   

app/views/users/edit.html.erb
<div class="container text-center">
<h3 class="mt-5">プロフィールを編集</h3>
<div class="mt-5"><%= image_tag @user.get_profile_image(200, 200), class: "rounded-circle" %></div>
<%= form_with model: @user do |f| %>
    
    <h6 class="col-lg-6"><%= f.file_field :profile_image, placeholder: "プロフィール画像を変更", accept: "image/*" %></h6>
    <label for="inputName">ユーザーネーム</label>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
    <label for="sailNo">セールナンバー</label>
    <%= f.text_field :sail_no, autofocus: true, id:"sailNo", placeholder:"セールナンバー" %>
    <label for="gerende">ゲレンデ</label>
    <%= f.text_field :gerende, autofocus: true, id:"gerende", placeholder:"ゲレンデ" %>
    <div>
        <%= f.submit "変更を保存",class: 'btn btn-secondary' %>
    </div>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>名前</th>
                <th>セールナンバー</th>
                <th>マイページ</th>
            </tr>
        </thead>
            <% @users.each do |user| %>
        <tbody>
            <tr>
                <td><%= user.name %></td>
                <td><%= user.sail_no %></td>
                <% if user == current_user %>
                    <td><%= link_to "マイページ", user_path(current_user.id),class: "btn btn-sm btn-danger" %></td>
                <% else %>
                    <td></td>
                <% end %>
            </tr>
        </tbody>
            <% end %>
    </table>
</div>

app/views/users/show.html.erb
<div class="container text-center">
    <div class="mt-5"><%= image_tag @user.get_profile_image(150, 200), class: "rounded-circle" %></div>
    <h3><%= @user.name %><%= @user.sail_no %></h3>
    <div class="row">
        <h5 class="col-6">ゲレンデ:<%= @user.gerende %></h5>
        <h5 class="col-6"><i class="fa-solid fa-pen-to-square"></i><%= link_to "プロフィール編集", edit_user_path,class: "btn btn-sm btn-danger" %></h5>
    </div>
    
    <div class="mt-4">
        <h4><%= Date.current.month %>月の出艇回数 <%= @departure_month.count %>回</h4>
    </div>
    
</div>